package style

import androidx.compose.ui.graphics.Color

// Monee design tokens
private val Accent = Color(0xFF1ED760)
private val AccentContent = Color(0xFF07110B)
private val LightBackground = Color(0xFFF7F8F6)
private val LightSurface = Color(0xFFFFFFFF)
private val LightTonalSurface = Color(0xFFEDF1ED)
private val LightText = Color(0xFF121713)
private val LightSecondaryText = Color(0xFF626D66)
private val LightBorder = Color(0xFFDCE4DE)
private val DarkBackground = Color(0xFF101512)
private val DarkSurface = Color(0xFF181F1B)
private val DarkTonalSurface = Color(0xFF202923)
private val DarkText = Color(0xFFF6FAF7)
private val DarkSecondaryText = Color(0xFFA7B0AA)
private val DarkBorder = Color(0xFF2C3730)
private val Error = Color(0xFFDC2626)
private val ErrorContainerLight = Color(0xFFFEE2E2)
private val ErrorContainerDark = Color(0xFF7F1D1D)

val primaryLight = Accent
val onPrimaryLight = AccentContent
val primaryContainerLight = Accent
val onPrimaryContainerLight = AccentContent
val secondaryLight = Color(0xFF4E6354)
val onSecondaryLight = LightSurface
val secondaryContainerLight = LightTonalSurface
val onSecondaryContainerLight = LightText
val tertiaryLight = Color(0xFF3F6650)
val onTertiaryLight = LightSurface
val tertiaryContainerLight = Color(0xFFC5E8D0)
val onTertiaryContainerLight = Color(0xFF0E3A20)
val errorLight = Error
val onErrorLight = LightSurface
val errorContainerLight = ErrorContainerLight
val onErrorContainerLight = Color(0xFF7F1D1D)
val backgroundLight = LightBackground
val onBackgroundLight = LightText
val surfaceLight = LightSurface
val onSurfaceLight = LightText
val surfaceVariantLight = LightTonalSurface
val onSurfaceVariantLight = LightSecondaryText
val outlineLight = Color(0xFF87938B)
val outlineVariantLight = LightBorder
val scrimLight = Color.Black
val inverseSurfaceLight = DarkText
val inverseOnSurfaceLight = DarkText
val inversePrimaryLight = Color(0xFF8BEFA8)

val primaryDark = Accent
val onPrimaryDark = AccentContent
val primaryContainerDark = Color(0xFF0D6B32)
val onPrimaryContainerDark = Color(0xFFB8F5C8)
val secondaryDark = Color(0xFFB5D2BC)
val onSecondaryDark = Color(0xFF203528)
val secondaryContainerDark = DarkTonalSurface
val onSecondaryContainerDark = DarkText
val tertiaryDark = Color(0xFFA9D5B6)
val onTertiaryDark = Color(0xFF163A22)
val tertiaryContainerDark = Color(0xFF2D5138)
val onTertiaryContainerDark = Color(0xFFC5E8D0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = ErrorContainerDark
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = DarkBackground
val onBackgroundDark = DarkText
val surfaceDark = DarkSurface
val onSurfaceDark = DarkText
val surfaceVariantDark = DarkTonalSurface
val onSurfaceVariantDark = DarkSecondaryText
val outlineDark = Color(0xFF87938B)
val outlineVariantDark = DarkBorder
val scrimDark = Color.Black
val inverseSurfaceDark = LightText
val inverseOnSurfaceDark = LightSurface
val inversePrimaryDark = Color(0xFF006D32)
